apiVersion: v1
kind: Service
metadata:
  name: {{ include "kerberos.fullname" . }}
  labels:
    {{- include "kerberos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 749
      targetPort: http
      protocol: TCP
      name: http
    - port: 88
      targetPort: port2
      protocol: UDP
      name: port2
  selector:
    {{- include "kerberos.selectorLabels" . | nindent 4 }}
